packages:
  - 'apps/*'
  - 'libs/*'
allowBuilds:
  '@parcel/watcher': true
  less: true
  nx: true
  sharp: true
  unrs-resolver: true
  '@nestjs/core': false
  '@prisma/engines': true
  prisma: true
  protobufjs: true
